version: '3.8'

services:
  avito_mx:
    container_name: avito_mx
    restart: unless-stopped
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=avito_mx
  postgres:
    container_name: pg_avito_mx
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avito_mx
